AWSTemplateFormatVersion: "2010-09-09" 
Description: Create EBS to HPC
Resources:
  EBS:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      Size: 80  
      VolumeType: gp2
      Tags:
        - Key: AppName
          Value: HPC
        - Key: environment
          Value: prod
        - Key: company
          Value: fca
        - Key: app-id
          Value: la00396
        - Key: business-unit
          Value: engineering
        - Key: cloud-provider
          Value: aws
        - Key: cost-center
          Value: 1234
        - Key: ito-provider
          Value: npo
        - Key: plataform
          Value: linux
        - Key: product
          Value: starccm
        - Key: security-group
          Value: sg-0c2b4ba342059bdf8
        - Key: distro
          Value: amazon